version: '3'
services:
  app:
    image: gentux/php:laravel-7.x-ci
    networks:
      - myapp
    volumes:
      - .:/var/www
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - "app:fpm.local"
    networks:
      - myapp
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: modules
      MYSQL_USER: modules
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - myapp
    ports:
      - "3306:3306"

networks:
  myapp: